### ISSUE TITLE
最新版本2.0.0 运行报错

### ISSUE THREAD

**Issue by OnlyTL** [jekip/naive-ui-admin#297]
步骤：
1. git clone ~~
2. pnpm install
3. pnpm run dev

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
Port 8001 is in use, trying another one...                                                                                                             20:11:33
                                                                                                                                                       20:11:33
  VITE v5.4.5  ready in 2696 ms

  ➜  Local:   http://localhost:8002/                                                                                                                   20:11:33
  ➜  Network: http://192.168.50.113:8002/                                                                                                              20:11:33
  ➜  Network: http://172.25.224.1:8002/                                                                                                                20:11:33
  ➜  Network: http://172.18.96.1:8002/                                                                                                                 20:11:33
  ➜  press h + enter to show help                                                                                                                      20:11:33

 ERROR  Error: The following dependencies are imported but could not be resolved:                                                                      20:11:34

  mock/system/menu (imported by D:/code/onlytl/naive-ui-admin/src/views/system/role/role.vue?id=0)

Are they installed?
    at file:///D:/code/onlytl/naive-ui-admin/node_modules/.pnpm/vite@5.4.5_@types+node@18.19.50_less@4.2.0_terser@5.32.0/node_modules/vite/dist/node/chunks/dep-CUvs3bbV.js:50603:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///D:/code/onlytl/naive-ui-admin/node_modules/.pnpm/vite@5.4.5_@types+node@18.19.50_less@4.2.0_terser@5.32.0/node_modules/vite/dist/node/chunks/dep-CUvs3bbV.js:50108:26

![image](https://github.com/user-attachments/assets/e2850c47-dc47-4f0d-9c7b-102c5de0a853)

**Comment by derline** [comment]
我这儿也是。这种低级问题，而且都4天了……

**Comment by jekip** [comment]
最近有些忙，抱歉了
