### ISSUE TITLE
首次运行报错：TypeError: Cannot read property 'endsWith' of undefined

### ISSUE THREAD

**Issue by xiaolv899** [jekip/naive-ui-admin#53]
Node v16.6.1
报这个错误，有可能是什么问题？ 
`
sdeMacBook-Pro:admin s$ yarn dev
yarn run v1.22.11
$ vite
failed to load config from /Users/s/Documents/test/mjxiu/cms/admin/vite.config.ts
error when starting dev server:
TypeError: Cannot read property 'endsWith' of undefined
    at configHtmlPlugin (/Users/s/Documents/test/mjxiu/cms/admin/vite.config.ts:215:34)
    at createVitePlugins (/Users/s/Documents/test/mjxiu/cms/admin/vite.config.ts:282:20)
    at vite_config_default (/Users/s/Documents/test/mjxiu/cms/admin/vite.config.ts:340:14)
    at loadConfigFromFile (/Users/s/Documents/test/mjxiu/cms/admin/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:75511:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolveConfig (/Users/s/Documents/test/mjxiu/cms/admin/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:75096:28)
    at async createServer (/Users/s/Documents/test/mjxiu/cms/admin/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:73625:20)
    at async CAC.<anonymous> (/Users/s/Documents/test/mjxiu/cms/admin/node_modules/vite/dist/node/cli.js:13963:24)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by jekip** [comment]
确保依赖安装成功，node版本，建议选择稳定版本，看着像是vite启动就报错了
